// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ScladCRUD.Models
{
    [Table("catalog1")]
    public partial class Catalog1
    {
        [Key]
        [Column("id_catalog")]
        public int IdCatalog { get; set; }
        [Column("id_product")]
        public int? IdProduct { get; set; }
        [Required]
        [Column("product_name")]
        [StringLength(50)]
        public string ProductName { get; set; }
        [Required]
        [Column("articul")]
        [StringLength(50)]
        public string Articul { get; set; }
        [Column("price")]
        [Precision(9, 2)]
        public decimal Price { get; set; }
        [Column("product_pic")]
        [StringLength(900)]
        public string ProductPic { get; set; }

        [ForeignKey("IdProduct")]
        [InverseProperty("Catalog1")]
        public virtual Product1 IdProductNavigation { get; set; }
    }
}