// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using StackExchange.Redis;

namespace ScladCRUD.Models
{
    [Table("client1")]
    public partial class Client1
    {
        public Client1()
        {
            Order1 = new HashSet<Order1>();
        }

        [Key]
        [Column("id_client")]
        public int IdClient { get; set; }
        [Required]
        [Column("client_name")]
        [StringLength(100)]
        public string ClientName { get; set; }
        [Required]
        [Column("post")]
        [StringLength(255)]
        public string Post { get; set; }
        [Required]
        [Column("tel")]
        [StringLength(20)]
        public string Tel { get; set; }
        [Required]
        [Column("parol")]
        [StringLength(50)]
        public string Parol { get; set; }
        [Required]
        [Column("avatar")]
        [StringLength(900)]
        public string Avatar { get; set; }
        public Role Role { get; set; }

        [InverseProperty("IdClientNavigation")]
        public virtual ICollection<Order1> Order1 { get; set; }
    }
}