// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ScladCRUD.Models
{
    [Table("order1")]
    public partial class Order1
    {
        [Key]
        [Column("id_order")]
        public int IdOrder { get; set; }
        [Column("id_product")]
        public int? IdProduct { get; set; }
        [Column("id_client")]
        public int? IdClient { get; set; }
        [Required]
        [Column("client_name")]
        [StringLength(100)]
        public string ClientName { get; set; }
        [Required]
        [Column("product_name")]
        [StringLength(50)]
        public string ProductName { get; set; }
        [Required]
        [Column("articul")]
        [StringLength(50)]
        public string Articul { get; set; }
        [Column("qantity")]
        public int Qantity { get; set; }

       
        [ForeignKey("IdProduct")]
        [InverseProperty("Order1")]
        public virtual Product1 IdProductNavigation { get; set; }
    }
}